INSERT INTO universite (nom_universite)
VALUES 
    ('Université de Montréal'),
    ('Université Laval'),
    ('Université du Québec à Montréal (UQAM)'),
    ('Université de Sherbrooke'),
    ('Université Concordia'),
    ('Université McGill'),
    ('Université du Québec à Trois-Rivières (UQTR)'),
    ('Université du Québec en Outaouais (UQO)'),
    ('Université du Québec à Chicoutimi (UQAC)'),
    ('Université du Québec à Rimouski (UQAR)'),
    ('Université du Québec à Hull (UQAH)'),
    ('Université du Québec à Longueuil (UQAL)'),
    ('Université du Québec en Abitibi-Témiscamingue (UQAT)'),
    ('Université du Québec en Estrie (UQAE)'),
    ('Université du Québec à Saint-Hyacinthe (UQASH)'),
    ('Université TÉLUQ'),
    ('Université de Montréal - HEC Montréal'),
    ('Institut national de la recherche scientifique (INRS)'),
    ('Université du Québec à Montréal - École des sciences de la gestion (ESG UQAM)'),
    ('Université du Québec à Montréal - Institut national de la recherche scientifique en eau (INRS Eau)'),
    ('Université du Québec en Outaouais - École nationale d''administration publique (ENAP)'),
    ('Université du Québec en Outaouais - Département des sciences administratives (UQO-DSA)'),
    ('Université du Québec en Outaouais - École de travail social (UQO-ÉTS)'),
    ('Université du Québec en Outaouais - Département de géographie (UQO-GEO)');
